config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'movies#index'

  get 'search' => 'search#search'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :movies, only: %i[index show]
  resources :users, only: %i[index show]

  resources :posts, only: %i[show destroy edit update]
  resources :movies, only: [:show] do
    resources :posts, only: %i[new create]
  end

  resources :posts do
    resource :like, only: %i[create destroy]
  end

  resources :search, only: %i[index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
# frozen_string_literal: true

class Genre < ApplicationRecord
  has_many :movie_genres, foreign_key: 'genre_id'
  has_many :movies, through: :movie_genres
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :post_id, uniqueness: { scope: :user_id }
end

app/models/movie.rb
# frozen_string_literal: true

class Movie < ApplicationRecord
  has_many :movie_genres, foreign_key: 'movie_id'
  has_many :genres, through: :movie_genres

  has_many :posts, dependent: :destroy
end

app/models/movie_genre.rb
# frozen_string_literal: true

class MovieGenre < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  validates :content, presence: true, length: { maximum: 500 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy

  validates :name, presence: true, length: { maximum: 20 }

  has_one_attached :image
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  def like?(post)
    likes.exists?(post: post)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email name password password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[email name password password_confirmation image])
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    like = current_user.likes.build(post: @post)
    like.save!
  end

  def destroy
    @post = Post.find(params[:post_id])
    like = current_user.likes.find_by(post: @post)
    like.destroy!
  end
end

app/controllers/movie_pages_controller.rb
class MoviePagesController < ApplicationController
  def index
    @movies = Movie.where.not(poster_path: '').order(popularity: "DESC").page(params[:page]).per(12)
  end

  def show
    @movie = Movie.find(params[:id])
  end
end

app/controllers/movies_controller.rb
# frozen_string_literal: true

class MoviesController < ApplicationController
  def index
    @movies = Movie.where.not(poster_path: '').order(popularity: 'DESC').page(params[:page]).per(12)
  end

  def show
    @movie = Movie.find(params[:id])
    @posts = @movie.posts.includes(:user)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]

  def new
    @movie = Movie.find(params[:movie_id])
    @post = @movie.posts.build
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @post = current_user.posts.build(post_params)
    @post.movie = @movie
    if @post.save
      redirect_to movie_path(params[:movie_id]), notice: '投稿を作成しました'
    else
      render :new, locals: { movie: @movie }
    end
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to movie_path(@post.movie_id), notice: '投稿を更新しました'
    else
      render :edit
    end
  end

  def destroy
    post = current_user.posts.find(params[:id])
    post.destroy!
    redirect_to movie_path(post.movie_id), notice: '投稿を削除しました'
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  require 'faraday'
  require 'json'

  API_KEY = Rails.application.credentials.api_key
  LANGUAGE = 'ja-JP'
  PAGE = 1
  REGION = 'JP'
  CONNECTION = Faraday.new('https://api.themoviedb.org/3/search/movie')

  def index; end

  def search
    if params[:keyword].present?
      movies = get_search_movie_json(params[:keyword])
      # @movies = []
      search_result_id = []
      # note:検索結果を全てDBに保存しており、効率が悪い
      # note:showで表示したものだけを保存したほうが良いのかも
      movies.each do |movie|
        MoviesAcquisitionApiSercvice.get_movie_save(movie)
        search_result_id.push(movie['id'])
      end
      # note:もっと綺麗な書き方がありそう。。。
      @movies = Movie.where(id: search_result_id).where.not(poster_path: '')
      render action: :index
    else
      redirect_back fallback_location: root_path
    end
  end

  private

  def get_search_movie_json(keyword)
    response = CONNECTION.get do |request|
      request.params[:api_key] = API_KEY
      request.params[:language] = LANGUAGE
      request.params[:query] = keyword
      request.params[:page] = PAGE
      request.params[:include_adult] = false
    end
    result = if response.success?
               JSON.parse(response.body)['results']
             else
               []
             end

    result.flatten
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def update_resource(resource, params)
    return super if params['password']&.present?

    resource.update_without_password(params.except('current_password'))
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/_flash.html.slim
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash")

app/views/layouts/_footer.html.slim
footer.page-footer.blue.darken-4
  .container
    .row
      .col.l6.s12
        h5.white-text ポートフォリオ
        p.grey-text.text-lighten-4 You can use rows and columns here to organize your footer content.
      .col.l4.offset-l2.s12
        h5.white-text 使用技術
        ul
          li Ruby on Rails
          li Docker
          li Circle CI(rubocop, RSpec, deploy)
  .footer-copyright
    .container
      | © 2020 Copyright Text

app/views/layouts/_header.html.slim
- if user_signed_in?
  ul#dropdown1.dropdown-content
    li#header-dropdown-1
      = link_to current_user.name, user_path(current_user)
    li#header-dropdown-2
      = link_to "ユーザ一覧", users_path
    li#header-dropdown-3
      = link_to "Logout", destroy_user_session_path, method: :delete
nav.blue.darken-4
  .nav-wrapper
    .brand-logo
      = link_to "Cinema Log", root_path, class: "logo"
    ul.right.hide-on-med-and-down
      li
        = link_to "映画一覧", root_path
      - if user_signed_in?
        li.plofile_image
          = link_to user_path(current_user) do
            - if current_user.image.attached? 
              = image_tag current_user.image, class: "circle responsive-img", id: "home-userimage"
            - else
              = image_tag "boy.png", class: "circle responsive-img"
        li
          a#header-dropdown_list.dropdown-trigger[href="#!" data-target="dropdown1"]
            i.material-icons
              | more_vert
      - else
        li
          = link_to "Login", new_user_session_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Cinema Log
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/header'
    #index-banner.section.no-pad-bot
      .container
        = render 'layouts/flash'
      .container
        .section
          = yield
    = render 'layouts/footer'

app/views/likes/create.js.erb
$("#like-post-<%= @post.id %>").html("<%= j(render partial: 'movies/like', locals: { post: @post }) %>");

app/views/likes/destroy.js.erb
$("#like-post-<%= @post.id %>").html("<%= j(render partial: 'movies/like', locals: { post: @post }) %>");

app/views/movie_pages/home.html.slim
.about-main
    .cinema-index-item
      .cinema-index-item
        h2.cinema-heading
          | 注目の映画
        - @movies.each do |movie|
          .cinema_image
            = link_to "/movie_pages/#{movie.id}" do
              - if movie.release_date.to_date > Date.today
                - if movie.poster_path == ''
                  = image_tag "no_image", class: "img-responsive", alt: "movie pic"
                - else
                  = image_tag "https://image.tmdb.org/t/p/w200#{movie.poster_path}",class: "img-responsive", alt: "movie pic"
                .caption
                  p
                    = movie.title
              - else
                - if movie.poster_path == ''
                  = image_tag "no_image", class: "img-responsive", alt: "movie pic"
                - else
                  = image_tag "https://image.tmdb.org/t/p/w200#{movie.poster_path}",class: "img-responsive", alt: "movie pic"
                .cinema_image_now
                  = image_tag "上映中.png", class: "now-img", alt: "movie pic"
                .caption
                  p
                    = movie.title
      h5.cinema-heading
        = paginate @movies

app/views/movies/_like.html.slim
- if current_user&.like?(post)
  = link_to post_like_path(post), method: :delete, class: 'post_unlike', remote: true do
    = fa_icon('heart', type: :solid)
  = post.likes.count
- else
  = link_to post_like_path(post), method: :post, class: 'post_like', remote: true do
    = fa_icon('heart', type: :regular)
  = post.likes.count

app/views/movies/_movie.html.slim
.col.s4
  = link_to movie_path(movie), id: "movie-id_#{movie.id}" do
    .card.hoverable
      .card-image
        - if movie.poster_path == ''
          = image_tag "no_image", alt: "movie pic"
        - else
          = image_tag "https://image.tmdb.org/t/p/w200#{movie.poster_path}", alt: "movie pic"
      .card-content
        span.card-title.grey-text.text-darken-4
          h6
            = movie.title

app/views/movies/_movie_detail.html.slim
.col-md-11[style="padding-left:20px;padding-right:20px;"]
  h4
    = @movie.title
  h5.center
    | 原題：
    = @movie.original_title
  p
    strong
      | 上映日：
    = @movie.release_date
  
  - unless @movie.run_time.blank?
    p
      strong
        | 上映時間：
      = @movie.run_time 
      | 分
  p
    strong
      | ジャンル：
    - @movie.genres.each do |genre|
      span
      = genre.name
      | 、
  p
    strong
      | ストーリ：<br>
    - if @movie.overview == ""
      span
      | 申し訳ございませんが、情報がありません。
    - else
      span
      = @movie.overview
    
  - unless @movie.video_key.blank?
    .trailers
     p
    strong
      | <br>予告動画：
      .row
        .col-md-6.col-sm-6
          - iframe = content_tag(:iframe, '', width: 300, height: 166, src: "https://www.youtube.com/embed/#{@movie.video_key}", frameborder: 0, allowfullscreen: true)
          = content_tag(:div, iframe, class: "youtube-container")

app/views/movies/_posts_index.html.slim
.post-index
  - posts.each do |post|
    - user = post.user
    .post-content
      .post-content-header
        - if current_user
          .post-user-image
            = link_to user_path(current_user) do
                - if current_user.image.attached? 
                  = image_tag current_user.image
                - else
                  = image_tag "boy.png"
        .post-user-name
          = link_to("#{user.name}の感想", user_path(user.id))
          p
            = post.updated_at.to_s[0, 16]
      .post-user-content
        = post.content
      hr
      .post-fotter
        .post-like
          div id = "like-post-#{post.id}"
            = render partial: 'like', locals: { post: post }
        .post-menu
          - if current_user && (current_user.id == post.user_id)
            = link_to edit_post_path(post.id), id: 'post-edit', title: '編集' do
              = fa_icon('edit', type: :solid)
            = link_to post_path(post.id), id: 'post-delete', title: '削除 ', method: :delete do
              = fa_icon('trash-alt', type: :solid)

app/views/movies/index.html.slim
.about-main
  = render 'search/search'
  .cinema-index-item.center-align
    h2.cinema-heading
      | 注目の映画
    .row
      - @movies.each do |movie|
        = render 'movies/movie', movie: movie
    h5.cinema-heading
      = paginate @movies

app/views/movies/show.html.slim
= provide(:title, "#{@movie.title}")
= provide(:title, "#{@movie.original_title}")
.row
  .col.s6
    = image_tag("https://image.tmdb.org/t/p/original#{@movie.poster_path}", :class => "responsive-img", :alt => "poster")
      = link_to new_movie_post_path(@movie.id), class: "btn-circle-3d", title: "コメントする！" do
        i.material-icons message
  .col.s6
      = render partial: 'movie_detail'
= render partial: 'posts_index', locals: { posts: @posts }

app/views/posts/edit.html.slim
.form-heading
  | 投稿の編集
.form
  .form-body
    - @post.errors.full_messages.each do |message|
      .form-error
        = message
    = form_with model: @post, url: post_path(@post.id), local: true do |f|
      = f.label :content, '投稿'
      = f.text_area :content
      = f.submit '更新する', class: "btn btn-primary"

app/views/posts/new.html.slim
.content1
  = image_tag "https://image.tmdb.org/t/p/w200#{@movie.poster_path}"
.content2
  .form-heading
    | 投稿する
  .form
    .form-body
      - @post.errors.full_messages.each do |message|
        .form-error
          = message
      = form_with model: @post, url: movie_posts_path, local: true do |form|
        = form.label :content, 'コメント'
        = form.text_area :content
        = form.submit "投稿", class: 'btn btn-primary'

app/views/search/_search.html.slim
#search_box.center-align
  = form_with url: search_path, method: :get, local: true do |f|
      .row.center-align
        .input-field
          i.material-icons.prefix search
          = f.text_field :keyword, class: "materialize-textarea", id: "icon_prefix2"
          label[for="icon_prefix2"]
            | 映画のタイトルを入力してください

app/views/search/index.html.slim
.about-main
  = render 'search/search'
  .cinema-index-item
    h2.cinema-heading
      | 検索結果
    - if @movies.present?
      - @movies.each do |movie|
        = render 'movies/movie', movie: movie
    - else
      h5 検索結果がありません

app/views/users/index.html.slim
div.users-index
  h1.users-heading
    | ユーザ一覧
  - @users.each do |user|
    hr.users-index-item
    .users-index-item
      = link_to(user.name,  "/users/#{user.id}")
  hr.users-index-item

app/views/users/shared/_error_messages.html.slim
- if resource.errors.any?
  #error_explanation
    h2
      = I18n.t("errors.messages.not_saved",
      -                  count: resource.errors.count,
      -                  resource: resource.class.model_name.human.downcase)
    ul
      - resource.errors.full_messages.each do |message|
        li
          = message

app/views/users/shared/_instant_login.html.slim
= form_with model: user, url: user_session_path, local: true do |f|
  = f.hidden_field :email, value: 'test@example.com'
  = f.hidden_field :password, value: 'testtest'
  = f.submit '簡単ログイン', class: 'btn btn-primary'

app/views/users/shared/_links.html.slim
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  br
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  br
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  br
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  br
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  br
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    br

app/views/users/show.html.slim
.user
  - if current_user.image.attached? 
    = image_tag current_user.image
  - else
    = image_tag "boy.png"
  h2
    = @user.name
  - if current_user && @user.id == current_user.id
    .square-content
      = link_to("編集", edit_user_registration_path , class: "square-btn")